Sleep 2500
Send h
Sleep 500
send /
Sleep 100
Send DSS Autopilot, hovercraft running. Please Don't interupt. APH0.1 This is an automated message.
Sleep 100
Send {enter}
send h
send l
send n

Send {w down}
Sleep 10430
Send {w up}

Send {d down}
Sleep 9000

Send {d up}
Sleep 11390

Send {d down}
Sleep 6000

Send {d up}
Sleep 12000
Send {d down}
Sleep 3000 
Send {d up}
Sleep 37000
